# Generated by Django 2.2.4 on 2019-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceplan',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
